### ISSUE TITLE
Using Python 3.9 error

### ISSUE THREAD

**Issue by websecnl** [makmour/url-http-status-bulk-check#2]
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='google.com%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E00FFB96D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by makmour** [comment]
Hey @websecnl ! Thanks a lot for the report. Do you receive the warning spontaneously or its a permanent one?
